name: C/C++ CI

on: 
  push:
    tags:
    - '*'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: version
      run: make version
    - name: make
      run: make
    - name: Create Release
      uses: ncipollo/release-action@v1.6.1
      with:
        artifacts: "dist/a.out"        
        token: ${{ secrets.GITHUB_TOKEN }}
