name: C/C++ CI

on: 
  push:
    tags:
    - '*'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.2'        
    - name: version
      run: make version
    - name: make
      run: make
    - name: Create Release
      uses: ncipollo/release-action@v1.6.1
      with:
        release_name: MyApp Linux
        artifacts: "dist/a.out"        
        token: ${{ secrets.GITHUB_TOKEN }}
